import registerPage from "../pageObjects/registerPage"

describe('template spec', () => {
  it('Verify Register Successfully', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    registerPage.enterFirstname('Joseph')
    registerPage.enterLastname('Bimanta')
    registerPage.enterEmail('joseph.qa4@gmail.com')
    registerPage.enterPassword('testingqa')
    registerPage.enterConfirmPassword('testingqa')
    registerPage.clickRegisterButton()
    registerPage.checkSuccessRegister()
  })

  it('Verify Register Failed - Didnt fill First Name field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    //registerPage.enterFirstname('Joseph')
    registerPage.enterLastname('Bimanta')
    registerPage.enterEmail('joseph.qa@gmail.com')
    registerPage.enterPassword('testingqa')
    registerPage.enterConfirmPassword('testingqa')
    registerPage.clickRegisterButton()
    registerPage.checkContainsErrorMessage('First name is required.')
  })

  it('Verify Register Failed - Didnt fill Last Name field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    registerPage.enterFirstname('Joseph')
    //registerPage.enterLastname('Bimanta')
    registerPage.enterEmail('joseph.qa@gmail.com')
    registerPage.enterPassword('testingqa')
    registerPage.enterConfirmPassword('testingqa')
    registerPage.clickRegisterButton()
    registerPage.checkContainsErrorMessage('Last name is required.')
  })

  it('Verify Register Failed - Didnt fill Email field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    registerPage.enterFirstname('Joseph')
    registerPage.enterLastname('Bimanta')
    //registerPage.enterEmail('joseph.qa@gmail.com')
    registerPage.enterPassword('testingqa')
    registerPage.enterConfirmPassword('testingqa')
    registerPage.clickRegisterButton()
    registerPage.checkContainsErrorMessage('Email is required.')
  })

  it('Verify Register Failed - Didnt fill Email field with valid credentials', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    registerPage.enterFirstname('Joseph')
    registerPage.enterLastname('Bimanta')
    registerPage.enterEmail('joseph.qagmail.com')
    registerPage.enterPassword('testingqa')
    registerPage.enterConfirmPassword('testingqa')
    registerPage.clickRegisterButton()
    registerPage.checkContainsErrorMessage('Wrong email')
  })

  it('Verify Register Failed - Didnt fill Password field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    registerPage.enterFirstname('Joseph')
    registerPage.enterLastname('Bimanta')
    registerPage.enterEmail('joseph.qa@gmail.com')
    //registerPage.enterPassword('testingqa')
    registerPage.enterConfirmPassword('testingqa')
    registerPage.clickRegisterButton()
    registerPage.checkContainsErrorMessage('Password is required.')
  })

  it('Verify Register Failed - Didnt fill Confirm Password field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    registerPage.enterFirstname('Joseph')
    registerPage.enterLastname('Bimanta')
    registerPage.enterEmail('joseph.qa@gmail.com')
    registerPage.enterPassword('testingqa')
    //registerPage.enterConfirmPassword('testingqa')
    registerPage.clickRegisterButton()
    registerPage.checkContainsErrorMessage('Password is required.')
  })

  it.only('Verify Register Failed - Password didnt match POM', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    registerPage.enterFirstname('Joseph')
    registerPage.enterLastname('Bimanta')
    registerPage.enterEmail('joseph.qa@gmail.com')
    registerPage.enterPassword('testingaja')
    registerPage.enterConfirmPassword('testingqa')
    registerPage.clickRegisterButton()
    registerPage.checkContainsErrorMessage('The password and confirmation password do not match.')
  })
})