describe('template spec', () => {
  it('Verify Register Successfully', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#FirstName').type('Joseph')
    cy.get('#LastName').type('Bimanta')
    cy.get('#Email').type('joseph.qa@gmail.com')
    cy.get('#Password').type('testingqa')
    cy.get('#ConfirmPassword').type('testingqa')
    cy.get('#register-button').click()
    cy.get('#register-button').should('contain,text', 'Your registration completed')
  })

  it('Verify Register Failed - Didnt fill First Name field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    //cy.get('#FirstName').type('Joseph')
    cy.get('#LastName').type('Bimanta')
    cy.get('#Email').type('joseph.qa@gmail.com')
    cy.get('#Password').type('testingqa')
    cy.get('#ConfirmPassword').type('testingqa')
    cy.get('#register-button').click()
    cy.contains('span', 'First name is required.')
  })

  it('Verify Register Failed - Didnt fill Last Name field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#FirstName').type('Joseph')
    //cy.get('#LastName').type('Bimanta')
    cy.get('#Email').type('joseph.qa@gmail.com')
    cy.get('#Password').type('testingqa')
    cy.get('#ConfirmPassword').type('testingqa')
    cy.get('#register-button').click()
    cy.contains('span', 'Last name is required.')
  })

  it('Verify Register Failed - Didnt fill Email field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#FirstName').type('Joseph')
    cy.get('#LastName').type('Bimanta')
    //cy.get('#Email').type('joseph.qa@gmail.com')
    cy.get('#Password').type('testingqa')
    cy.get('#ConfirmPassword').type('testingqa')
    cy.get('#register-button').click()
    cy.contains('span', 'Email is required.')
  })

  it('Verify Register Failed - Didnt fill Email field with valid credentials', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#FirstName').type('Joseph')
    cy.get('#LastName').type('Bimanta')
    cy.get('#Email').type('joseph.qagmail.com')
    cy.get('#Password').type('testingqa')
    cy.get('#ConfirmPassword').type('testingqa')
    cy.get('#register-button').click()
    cy.contains('span', 'Wrong email')
  })

  it('Verify Register Failed - Didnt fill Password field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#FirstName').type('Joseph')
    cy.get('#LastName').type('Bimanta')
    cy.get('#Email').type('joseph.qa@gmail.com')
    //cy.get('#Password').type('testingqa')
    cy.get('#ConfirmPassword').type('testingqa')
    cy.get('#register-button').click()
    cy.contains('span', 'Password is required.')
  })

  it('Verify Register Failed - Didnt fill Confirm Password field', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#FirstName').type('Joseph')
    cy.get('#LastName').type('Bimanta')
    cy.get('#Email').type('joseph.qa@gmail.com')
    cy.get('#Password').type('testingqa')
    //cy.get('#ConfirmPassword').type('testingqa')
    cy.get('#register-button').click()
    cy.contains('span', 'Password is required.')
  })

  it.only('Verify Register Failed - Password didnt match', () => {
    cy.clearCookies()
    cy.visit('https://demowebshop.tricentis.com/')
    cy.get('.ico-register').click()
    cy.get('#FirstName').type('Joseph')
    cy.get('#LastName').type('Bimanta')
    cy.get('#Email').type('joseph.qa@gmail.com')
    cy.get('#Password').type('testingaja')
    cy.get('#ConfirmPassword').type('testingqa')
    cy.get('#register-button').click()
    cy.contains('span', 'The password and confirmation password do not match.')
  })
})